In [11]:
import csv
import numpy as np
import matplotlib.pyplot as plt

data=[]
y=[]
with open('framingham.csv','r') as file:
    csv_reader=csv.reader(file)
    for line in csv_reader:
        data_row=[]
        if (line[0]!='male'):
            for i in range(15):
                if line[i]!='NA':
                    data_row.append(float(line[i]))
                else:
                    data_row.append(-1)
            data.append(data_row)
            y.append(int(line[15]))

data=np.array(data)
data=data.T

data_mean=np.mean(data,axis=1)
n1=0
n2=0
for i in data:
    n2=0
    for j in i:
        if j==-1:
            data[n1][n2]=data_mean[n1]
        n2+=1
    n1+=1
y=np.array(y).reshape(1,data.shape[1])        

In [12]:
w=np.zeros((1,15))
b=np.zeros((1,1))
ones=np.ones((1,data.shape[1])) 
data_mean=np.mean(data,axis=1).reshape(-1,1)
data_std=np.std(data,axis=1).reshape(-1,1)

data_temp=(data-np.matmul(data_mean,ones))/np.matmul(data_std,ones)

alpha=0.001
iter=1000

for i in range(iter):
       
    z=np.matmul(w,data_temp)+np.matmul(b,ones)

    y_hat=np.exp(z)/(ones+np.exp(z))

    delta=y_hat-y

    cost=(1-y)*np.log(1-y_hat)+y*y_hat

    w=w-alpha*np.matmul(delta,data_temp.T)/data.shape[1]

    b=b-alpha*np.mean(delta)

print(w)
print(b)
print(y_hat)

[[ 0.02759583  0.06452286 -0.01342366  0.00846777  0.02019172  0.0217631
   0.01776997  0.04394696  0.02571441  0.02030631  0.05554674  0.03321132
   0.01563165  0.00365101  0.03373981]]
[[-0.30829491]]
[[0.36188163 0.39170483 0.42023671 ... 0.40435691 0.39434659 0.41675266]]


In [13]:
one1=0 #ones in y
one2=0 #ones in y_predicted
for i in range(data.shape[1]):
    if y_hat[0][i]>=0.474:    #0.474 used to increase the sensitivity
        y_hat[0][i]=1
        one2+=1
    else:
        y_hat[0][i]=0

    if y[0][i]==1:
        one1+=1
print(y)
print(y_hat)
print(one1)
print(one2)

[[0 0 0 ... 0 0 0]]
[[0. 0. 0. ... 0. 0. 0.]]
644
640
