In [40]:
import matplotlib.pyplot as plt
import numpy as np

data=np.array([[73,91,87,102,69,74,91,88,101,68,73,92,87,103,68],[67,88,134,43,96,66,87,134,44,96,66,87,135,43,97],[43,64,58,37,70,43,65,59,37,71,44,64,57,36,70]])
y=np.array([[56,81,119,22,103,57,80,118,21,104,57,82,118,20,102],[70,101,133,37,119,69,102,132,38,118,69,100,134,38,120]])

data_std=np.std(data,axis=1).reshape(3,1)
y_std=np.std(y,axis=1).reshape(2,1)

data_mean=np.mean(data,axis=1).reshape(3,1)
y_mean=np.mean(y,axis=1).reshape(2,1)

w=np.zeros((2,3))
b=np.zeros((2,1))
# ones=np.ones(len(data[0])).reshape(1,15)
ones=np.ones((1,15))

data_temp=(data-np.matmul(data_mean,ones))/(np.matmul(data_std,ones))
y_temp=(y-np.matmul(y_mean,ones))/(np.matmul(y_std,ones))

learning_rate=0.00001
iter=100000
for i in range(iter):
    
    y_predicted=np.matmul(w,data_temp)+np.matmul(b,ones)

    delta=y_predicted-y_temp
    
    gradient=np.matmul(delta,data_temp.transpose())*(2/len(data[0]))
    
    temp_w=w-learning_rate*gradient
    
    temp_b=b-(2*learning_rate/len(data[0]))*np.sum(delta,axis=1,keepdims = True)

    w=temp_w
    b=temp_b

print((np.matmul(w,np.array([data_temp[0][3],data_temp[1][3],data_temp[2][3]]).reshape(3,1))+b)*y_std + y_mean)

[[-0.579901   -0.63724853]
 [ 0.14497525  0.26069258]
 [ 1.24678715  1.18759954]
 [-1.5657327  -1.59312133]
 [ 0.78286635  0.78207774]
 [-0.55090595 -0.66621437]
 [ 0.1159802   0.28965842]
 [ 1.2177921   1.1586337 ]
 [-1.59472775 -1.56415549]
 [ 0.8118614   0.7531119 ]
 [-0.55090595 -0.66621437]
 [ 0.1739703   0.23172674]
 [ 1.2177921   1.21656538]
 [-1.6237228  -1.56415549]
 [ 0.7538713   0.81104359]]
[[-0.54142049]
 [-0.60561057]]
[[0.23395718]
 [0.28298704]]
[[1.00954388]
 [1.0074181 ]]
[[-1.5594768 ]
 [-1.53961254]]
[[0.84913221]
 [0.84328563]]
